### ISSUE TITLE
Failed for matt

### ISSUE THREAD

**Issue by werebus** [umts/our-boxen#1]
Running on `ssid-umass-vl914-172-30-11-117.wireless.umass.edu` (OS X 10.12.5) under `/bin/bash`, version d79b9410812bfdd0450b24adbca9a073011f911c ([compare to master](https://github.com/umts/our-boxen/compare/d79b9410812bfdd0450b24adbca9a073011f911c...master)).

### Puppet Command

```
/opt/boxen/repo/bin/puppet apply --group admin --confdir /tmp/boxen/puppet/conf --vardir /tmp/boxen/puppet/var --libdir /opt/boxen/repo/lib --libdir /opt/boxen/repo/.bundle/ruby/2.0.0/gems/boxen-2.9.0/lib --modulepath /opt/boxen/repo/modules:/opt/boxen/repo/shared --hiera_config /opt/boxen/repo/config/hiera.yaml --logdest /opt/boxen/repo/log/boxen.log --logdest console --no-report --detailed-exitcodes --show_diff /opt/boxen/repo/manifests
```

### Output (from /opt/boxen/repo/log/boxen.log)

```
2017-05-26 14:41:57 -0400 Puppet (err): Unable to set ownership of log file
2017-05-26 14:42:05 -0400 Puppet (notice): Compiled catalog for ssid-umass-vl914-172-30-11-117.wireless.umass.edu in environment production in 3.99 seconds
2017-05-26 14:42:06 -0400 /Stage[main]/Boxen::Config/File[/opt/boxen/bin]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Boxen::Config/File[/opt/boxen/data]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Boxen::Config/File[/opt/boxen/data/project-sockets]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Boxen::Config/File[/opt/boxen/data/puppet]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Boxen::Config/File[/opt/boxen/log]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Boxen::Config/File[/opt/boxen/env.d]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Ruby/Boxen::Env_script[ruby]/File[/opt/boxen/env.d/30_ruby.sh]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Boxen::Config/File[/opt/boxen/README.md]/ensure (notice): defined content as '{md5}36be20bef1e05e4d42bf2243c0ff4368'
2017-05-26 14:42:06 -0400 /Stage[main]/Boxen::Config/File[/opt/boxen/env.sh]/ensure (notice): defined content as '{md5}69e7ff4eb2c6e72c15025660fdb20af2'
2017-05-26 14:42:06 -0400 /Stage[main]/Hub/Boxen::Env_script[hub]/File[/opt/boxen/env.d/70_hub.sh]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Nodejs/Boxen::Env_script[nodejs]/File[/opt/boxen/env.d/30_nodejs.sh]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Boxen::Config/File[/opt/boxen/cache]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Nodejs::Build/File[/opt/boxen/cache/nodes]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Ruby::Build/File[/opt/boxen/cache/rubies]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Homebrew/File[/usr/local/Library/Taps/boxen]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Homebrew/File[/usr/local/Library/Taps/boxen/homebrew-brews]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Homebrew/File[/opt/boxen/cache/homebrew]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Homebrew/File[/usr/local/Library/Taps/boxen/homebrew-brews/cmd]/ensure (notice): created
2017-05-26 14:42:06 -0400 /Stage[main]/Homebrew/File[/usr/local/Library/Taps/boxen/homebrew-brews/cmd/boxen-bottle-hooks.rb]/ensure (notice): defined content as '{md5}d4342ff99b81df9954412430a1f20c36'
2017-05-26 14:42:06 -0400 /Stage[main]/Homebrew/File[/usr/local/Library/Taps/boxen/homebrew-brews/cmd/brew-boxen-install.rb]/ensure (notice): defined content as '{md5}a4beded3206823a5c06301cf3b1c47a5'
2017-05-26 14:42:07 -0400 /Stage[main]/Git/File[/opt/boxen/bin/boxen-git-credential]/ensure (notice): created
2017-05-26 14:42:08 -0400 /Stage[main]/Nodejs::Build/Repository[/opt/boxen/node-build]/ensure (notice): created
2017-05-26 14:42:09 -0400 /Stage[main]/Ruby::Build/Repository[/opt/boxen/ruby-build]/ensure (notice): created
2017-05-26 14:42:09 -0400 /Stage[main]/Nodejs::Nodenv/Repository[/opt/boxen/nodenv]/ensure (notice): created
2017-05-26 14:42:09 -0400 /Stage[main]/Nodejs::Nodenv/File[/opt/boxen/nodenv/versions]/ensure (notice): created
2017-05-26 14:42:09 -0400 /Stage[main]/Git/File[/opt/boxen/config/git]/ensure (notice): created
2017-05-26 14:42:09 -0400 /Stage[main]/Git/File[/opt/boxen/config/git/gitignore]/ensure (notice): defined content as '{md5}0ee4680836d3ec216505fea423819550'
2017-05-26 14:42:10 -0400 /Stage[main]/Ruby::Rbenv/Repository[/opt/boxen/rbenv]/ensure (notice): created
2017-05-26 14:42:10 -0400 /Stage[main]/Ruby::Rbenv/File[/opt/boxen/rbenv/versions]/ensure (notice): created
2017-05-26 14:42:10 -0400 /Stage[main]/Homebrew/File[/usr/local/Library/Taps/boxen/homebrew-brews/cmd/brew-boxen-latest.rb]/ensure (notice): defined content as '{md5}17c81cf41ea3f014b34f4b83fe65e9d4'
2017-05-26 14:42:11 -0400 /Stage[main]/Homebrew/Boxen::Env_script[homebrew]/File[/opt/boxen/env.d/10_homebrew.sh]/ensure (notice): created
2017-05-26 14:42:11 -0400 /Stage[main]/Gcc/Homebrew::Formula[gcc5]/File[/usr/local/Library/Taps/boxen/homebrew-brews/gcc5.rb]/ensure (notice): defined content as '{md5}5d338ecc9c0fa82904a0655c12058650'
2017-05-26 14:42:11 -0400 /Stage[main]/Git/Homebrew::Formula[git]/File[/usr/local/Library/Taps/boxen/homebrew-brews/git.rb]/ensure (notice): defined content as '{md5}5d4b8d0c591448ffeabd9e9568c429fb'
2017-05-26 14:42:11 -0400 /Stage[main]/Hub/Homebrew::Formula[hub]/File[/usr/local/Library/Taps/boxen/homebrew-brews/hub.rb]/ensure (notice): defined content as '{md5}a2f97433e3fc51b05ece9fc9df0765e6'
2017-05-26 14:42:22 -0400 /Stage[main]/Boxen::Repo/Exec[clone /opt/boxen/repo]/returns (notice): executed successfully
2017-05-26 14:42:22 -0400 /Stage[main]/Boxen::Bin/File[/opt/boxen/bin/boxen]/ensure (notice): created
2017-05-26 14:42:22 -0400 /Stage[main]/Boxen::Config/File[/opt/boxen/data/puppet/graphs]/ensure (notice): created
2017-05-26 14:42:22 -0400 /Stage[main]/Boxen::Environment/Boxen::Env_script[relative_bin_on_path]/File[/opt/boxen/env.d/90_relative_bin_on_path.sh]/ensure (notice): defined content as '{md5}3188ce9906769eaa4bac6b0b4844d88e'
2017-05-26 14:42:22 -0400 /Stage[main]/Boxen::Environment/Boxen::Env_script[boxen_autocomplete]/File[/opt/boxen/env.d/90_boxen_autocomplete.sh]/ensure (notice): created
2017-05-26 14:42:22 -0400 /Stage[main]/Boxen::Environment/Boxen::Env_script[config]/File[/opt/boxen/env.d/10_config.sh]/ensure (notice): created
2017-05-26 14:42:22 -0400 /Stage[main]/Boxen::Environment/Boxen::Env_script[gh_creds]/File[/opt/boxen/env.d/30_gh_creds.sh]/ensure (notice): created
2017-05-26 14:42:22 -0400 Puppet (err): install failed with a crazy error: Execution of '/opt/boxen/node-build/bin/node-build 7.10.0 /opt/nodes/7.10.0' returned 2: node-build: definition not found: 7.10.0 ["/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/execution.rb:203:in `execute'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/provider.rb:115:in `execute'", "/opt/boxen/repo/shared/nodejs/lib/puppet/provider/nodejs/nodebuild.rb:66:in `build_node'", "/opt/boxen/repo/shared/nodejs/lib/puppet/provider/nodejs/nodebuild.rb:45:in `create'", "/opt/boxen/repo/shared/nodejs/lib/puppet/type/nodejs.rb:5:in `block (3 levels) in <top (required)>'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/property.rb:197:in `call_valuemethod'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/property.rb:498:in `set'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/property.rb:581:in `sync'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction/resource_harness.rb:204:in `sync'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction/resource_harness.rb:128:in `sync_if_needed'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction/resource_harness.rb:81:in `perform_changes'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction/resource_harness.rb:20:in `evaluate'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:204:in `apply'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:217:in `eval_resource'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:147:in `call'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:147:in `block (2 levels) in evaluate'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util.rb:327:in `block in thinmark'", "/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util.rb:326:in `thinmark'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:147:in `block in evaluate'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/graph/relationship_graph.rb:118:in `traverse'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:138:in `evaluate'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/resource/catalog.rb:169:in `block in apply'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/log.rb:149:in `with_destination'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction/report.rb:112:in `as_logging_destination'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/resource/catalog.rb:168:in `apply'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/configurer.rb:118:in `block in apply_catalog'", "/opt/boxen/repo/shared/boxen/lib/puppet/provider/package/hax.rb:12:in `benchmark'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/configurer.rb:117:in `apply_catalog'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/configurer.rb:222:in `run_internal'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/configurer.rb:132:in `block in run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/context.rb:64:in `override'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet.rb:244:in `override'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/configurer.rb:131:in `run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application/apply.rb:297:in `apply_catalog'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application/apply.rb:231:in `block in main'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/context.rb:64:in `override'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet.rb:244:in `override'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application/apply.rb:193:in `main'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application/apply.rb:154:in `run_command'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application.rb:384:in `block (2 levels) in run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application.rb:510:in `plugin_hook'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application.rb:384:in `block in run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util.rb:488:in `exit_on_fail'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application.rb:384:in `run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/command_line.rb:146:in `run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/command_line.rb:92:in `execute'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/bin/puppet:8:in `<top (required)>'", "/opt/boxen/repo/bin/puppet:16:in `load'", "/opt/boxen/repo/bin/puppet:16:in `<main>'"]
2017-05-26 14:42:22 -0400 /Stage[main]/Main/Node[default]/Nodejs::Version[7.10.0]/Nodejs[7.10.0]/ensure (err): change from absent to present failed: install failed with a crazy error: Execution of '/opt/boxen/node-build/bin/node-build 7.10.0 /opt/nodes/7.10.0' returned 2: node-build: definition not found: 7.10.0 ["/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/execution.rb:203:in `execute'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/provider.rb:115:in `execute'", "/opt/boxen/repo/shared/nodejs/lib/puppet/provider/nodejs/nodebuild.rb:66:in `build_node'", "/opt/boxen/repo/shared/nodejs/lib/puppet/provider/nodejs/nodebuild.rb:45:in `create'", "/opt/boxen/repo/shared/nodejs/lib/puppet/type/nodejs.rb:5:in `block (3 levels) in <top (required)>'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/property.rb:197:in `call_valuemethod'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/property.rb:498:in `set'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/property.rb:581:in `sync'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction/resource_harness.rb:204:in `sync'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction/resource_harness.rb:128:in `sync_if_needed'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction/resource_harness.rb:81:in `perform_changes'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction/resource_harness.rb:20:in `evaluate'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:204:in `apply'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:217:in `eval_resource'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:147:in `call'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:147:in `block (2 levels) in evaluate'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util.rb:327:in `block in thinmark'", "/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util.rb:326:in `thinmark'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:147:in `block in evaluate'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/graph/relationship_graph.rb:118:in `traverse'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction.rb:138:in `evaluate'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/resource/catalog.rb:169:in `block in apply'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/log.rb:149:in `with_destination'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/transaction/report.rb:112:in `as_logging_destination'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/resource/catalog.rb:168:in `apply'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/configurer.rb:118:in `block in apply_catalog'", "/opt/boxen/repo/shared/boxen/lib/puppet/provider/package/hax.rb:12:in `benchmark'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/configurer.rb:117:in `apply_catalog'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/configurer.rb:222:in `run_internal'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/configurer.rb:132:in `block in run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/context.rb:64:in `override'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet.rb:244:in `override'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/configurer.rb:131:in `run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application/apply.rb:297:in `apply_catalog'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application/apply.rb:231:in `block in main'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/context.rb:64:in `override'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet.rb:244:in `override'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application/apply.rb:193:in `main'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application/apply.rb:154:in `run_command'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application.rb:384:in `block (2 levels) in run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application.rb:510:in `plugin_hook'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application.rb:384:in `block in run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util.rb:488:in `exit_on_fail'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/application.rb:384:in `run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/command_line.rb:146:in `run'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/lib/puppet/util/command_line.rb:92:in `execute'", "/opt/boxen/repo/.bundle/ruby/2.0.0/gems/puppet-3.7.1/bin/puppet:8:in `<top (required)>'", "/opt/boxen/repo/bin/puppet:16:in `load'", "/opt/boxen/repo/bin/puppet:16:in `<main>'"]
2017-05-26 14:52:25 -0400 /Stage[main]/Main/Node[default]/Ruby::Version[2.3.4]/Ruby[2.3.4]/ensure (notice): created

```

**Comment by werebus** [comment]
Succeeded at version 0463ef45f5b803fd79793c388631c11c408104d0.

**Comment by dfaulken** [comment]
Are these auto-generated?

**Comment by werebus** [comment]
Yup.  https://github.com/umts/our-boxen/blob/master/config/boxen.rb#L16
